modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "qoofix"
description = '''
Set any cape by URL - visible to all EasyCapes players, instant updates.
'''
logoFile = "assets/easycapes/icon.png"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft},)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "easycapes.mixins.json"
